export const THEME_COLORS = {
  primary: '#0f5238',
  onPrimary: '#ffffff',
  primaryContainer: '#2d6a4f',
  onPrimaryContainer: '#a8e7c5',
  secondary: '#006c48',
  secondaryContainer: '#92f7c3',
  onSecondaryContainer: '#00734d',
  tertiary: '#5f4035',
  tertiaryContainer: '#79574c',
  background: '#f9faf2',
  surface: '#ffffff',
  surfaceContainerLow: '#f3f4ec',
  surfaceContainer: '#edefe7',
  surfaceContainerHigh: '#e8e9e1',
  surfaceContainerHighest: '#e2e3db',
  outline: '#707973',
  outlineVariant: '#bfc9c1',
  error: '#ba1a1a',
  errorContainer: '#ffdad6',
  warning: '#f57c00',
  warningContainer: '#fff8e1',
  warningBorder: '#ffd54f',
};
